sudo: required
services:
  - docker

before_install:
  - docker build -t mozam/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true mozam/react-test npm run test -- --coverage

after_success:
  - docker build - t mozam/multi-client -f ./client/Dockerfile ./client
  - docker build - t mozam/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build - t mozam/multi-server -f ./server/Dockerfile ./server
  - docker build - t mozam/multi-worker -f ./worker/Dockerfile ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mozam/multi-client
  - docker push mozam/multi-nginx
  - docker push mozam/multi-server
  - docker push mozam/multi-worker
